### PR TITLE
Add PyBullet driver for Solo12

### PR DESCRIPTION
**Pull request by luator**
## Description

Add an alternative driver that uses the PyBullet simulation instead of connecting to a real robot.
A new demo `demo_solo12_simulation` illustrates its use.

Some refactoring and changes were done to make this fit in. Most importantly, `create_solo12_backend` has been made more generic and the old version is renamed to `create_real_solo12_backend`.

## How I Tested
By running the new demo and `solo12_show_data --sim`.

## Do not merge before
- https://github.com/open-dynamic-robot-initiative/robot_properties_solo/pull/55

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by luator** [comment]
@ahmadgazar @majidkhadiv I think you can focus on the `PyBulletSolo12Driver` class (it would be good if someone double-checks that I am accessing the simulation in the right way) and see `demo_solo12_simulation.py` for a usage example.

To just run the simulation with a controller holding the joints in place while printing all sensor data, you can run `ros2 run robot_interfaces_solo solo12_show_data --sim`.

So far I only tested whether it is generally running and looking good but did not in detail verify if, e.g. all the joint values are reported correctly.

**Comment by ahmadgazar** [comment]
Thanks a lot for your effort @luator. I will check that this week once I install the package in the container. I already have some motions I want to test anyways to check if everything is working as expected.

**Comment by ahmadgazar** [comment]
hi @luator. I ran into an issue while running the demo you mentioned above. I pulled the latest apptainer container image, then ran :
` apptainer run -e solo_robot_latest.sif ros2 run robot_interfaces_solo solo12_show_data --sim`
 
the output is:
image.

I tried to run the demo without `--sim` and added the config.yaml file from robot_properties_solo pkg as follows:
`apptainer run -e solo_robot_latest.sif ros2 run robot_interfaces_solo solo12_show_data --sim ./home/agazar/devel_colcon/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/dynamic_graph_manager/dgm_parameters_solo12_mpi_is.yaml`,  but I got:
image.  Any ideas about what I might be doing wrong?

**Comment by luator** [comment]
Since you are using the "solo_robot" container, I assume you did not set up a local workspace for this?  In this case it wouldn't work, as the changes of this pull request are not yet merged and thus not included in the container.  Instead you need to follow the ["For Development"](https://github.com/open-dynamic-robot-initiative/robot_interfaces_solo#for-development) section in the README and after running `treep --clone` checkout this branch (e.g. with `treep --checkout-branch fwidmaier/pybullet`) before you build the workspace.

The config file you need to pass to `solo12_show_data` is not the same as for the dynamic graph, you need to create a new one (see "Configuration" section in the README).  On the real robot, the only mandatory argument is `network_interface`.  For simulation even this is not needed, so you can simply pass an empty file (however, it still has to exist, otherwise `solo12_show_data` will fail).

However, the "bad file" error in your case suggests that the path you provided is wrong (I assume due to the dot at the beginning).

**Comment by ahmadgazar** [comment]
hi @luator. As I mentioned in our private discussion, I successfully managed to build the package using clang instead of gcc. Everything seems to be working good with pull request demo. I also checked the joint positions and velocities against the quantities obtained from `solo12wrapper`, so you are accessing them correctly. 

Minor comment: classically we set the robot's initial configuration with the base centered at the world frame of pybullet, which is not currently the case.  This can bse when initializing `robot_interfaces_solo.PyBulletDriver` may be? Otherwise an option to start at a desired base position might be helpful.

I have another minor comment related to the convenience of accessing the base state directly from the simulator without relying on the `solo12wrapper` to avoid adding redundant dependencies, but we can chat about this privately in another issue better.  Apart from that, things are good from my side, thanks for your effort.

**Comment by ahmadgazar** [comment]
hi @luator. As I mentioned in our private discussion, I successfully managed to build the package using clang instead of gcc. Everything seems to be working good with pull request demo. I also checked the joint positions and velocities against the quantities obtained from `solo12wrapper`, so you are accessing them correctly. 

Minor comment: classically we set the robot's initial configuration with the base centered at the world frame of pybullet, which is not currently the case.  This can be done when initializing `robot_interfaces_solo.PyBulletDriver` may be? Otherwise an option to start at a desired base position might be helpful.

I have another minor comment related to the convenience of accessing the base state directly from the simulator without relying on the `solo12wrapper` to avoid adding redundant dependencies, but we can chat about this privately in another issue better.  Apart from that, things are good from my side, thanks for your effort.

**Review by ahmadgazar — APPROVED** [review]

**Comment by luator** [comment]
@ahmadgazar Thanks a lot for testing!

Regarding the initial position:  I followed the demo and use the values from [`Solo12Config.initial_configuration`](https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/f321c7fdad8ae77c8a9b91638fa77d5cca5bbfc0/src/robot_properties_solo/config.py#L247) to initialise the robot.  This sets the base to (0.2, 0.0, 0.25).  Would it make sense to change it there, if one typically rather wants to have the robot at the origin?

Currently, it should already be possible to set the base to a different position by calling `reset_state()` of the wrapper with a custom value before sending actions.
Is starting at a non-default position is a common use case?  If yes, I can also look into adding it directly to the driver but if it is only needed in some special cases, I think resetting via the sim env should be sufficient.

**Comment by ahmadgazar** [comment]
> Currently, it should already be possible to set the base to a different position by calling `reset_state()` of the wrapper with a custom value before sending actions.
> Is starting at a non-default position is a common use case? If yes, I can also look into adding it directly to the driver but if it is only needed in some special cases, I think resetting via the sim env should be sufficient.

That's true, it's quite trivial actually, never mind then :)).

**Comment by luator** [comment]
I found a workaround for the GCC error (see latest commit), so compiling with GCC works as well now.

**Pull request merged**
